name: Integracion Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verificar Backend
        run: |
          cd backend
          npm install

      - name: Verificar y Compilar Frontend
        run: |
          cd frontend
          npm install
          npm run build